# Generated by Django 2.0.12 on 2019-10-24 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tao',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
