# Generated by Django 2.0.12 on 2019-10-28 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0002_auto_20191024_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='类型')),
                ('active', models.BooleanField(default=False, verbose_name='是否启动')),
                ('comprehensive', models.CharField(max_length=20, verbose_name='综合')),
                ('shoe', models.CharField(max_length=20, verbose_name='鞋包配饰')),
                ('mother', models.CharField(max_length=20, verbose_name='母婴')),
                ('ladies', models.CharField(max_length=20, verbose_name='女装')),
                ('makeup', models.CharField(max_length=20, verbose_name='美妆个护')),
                ('food', models.CharField(max_length=20, verbose_name='食品')),
                ('furnishing', models.CharField(max_length=20, verbose_name='家居家装')),
                ('mens', models.CharField(max_length=20, verbose_name='男装')),
                ('sports', models.CharField(max_length=20, verbose_name='运动户外')),
                ('digita', models.CharField(max_length=20, verbose_name='数码家电')),
                ('underwear', models.CharField(max_length=20, verbose_name='内衣')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AddField(
            model_name='tao',
            name='adzone_id',
            field=models.CharField(default='', max_length=60, verbose_name='adzone_id'),
        ),
    ]
