# Generated by Django 2.0.12 on 2019-10-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0005_auto_20191029_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='img',
            field=models.URLField(default='', verbose_name='图片地址'),
        ),
    ]
