# Generated by Django 2.0.12 on 2019-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taobao', '0006_banner_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.TextField(verbose_name='跳转地址'),
        ),
    ]
