# Generated by Django 2.0.12 on 2019-11-04 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jd_app', '0003_auto_20191104_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='活动名称')),
                ('url', models.TextField(verbose_name='跳转地址')),
                ('img', models.URLField(default='', verbose_name='图片地址')),
                ('start_time', models.DateField(default=datetime.datetime.now, verbose_name='活动开始时间')),
                ('end_time', models.DateField(default=datetime.datetime.now, verbose_name='活动结束时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '活动',
                'verbose_name_plural': '活动',
            },
        ),
    ]
